function modifiedCh = modifyChannel3(ch)
% Extra chanel for Zrotation for index lower joint

ch_size = size(ch);
padding = zeros(ch_size(1), 10);

dang = 0.5 * [ch(:, 11) ch(:, 15) ch(:, 19)];
% A little bit of magic
abs_abd = [dang(:, 1), dang(:, 2:3) - dang(:, 1:2), -dang(:, 3)];

ch = [ch(:, 1:7), abs_abd(:, 1), ch(:, 8:10), abs_abd(:, 2), ch(:, 12:14), ...
    abs_abd(:, 3), ch(:, 16:18), abs_abd(:, 4), ch(:, 20:22)];

modifiedCh = [padding(:,1:6), ...
    padding(:,1), ch(:,22:23), ...
    padding(:,1:3), ...
    padding(:,1:3), ch(:,1), padding(:,1), ch(:,4), ...
    padding(:,1:2), ch(:,2), ...
    padding(:,1:2), ch(:,3), ...
    padding(:,1:4), ch(:,5), ch(:,8), ...
    padding(:,1), ch(:,6), padding(:,1), ...
    padding(:,1), ch(:,7), padding(:,1), ...
    padding(:,1:4), ch(:,9), ch(:,12), ...
    padding(:,1), ch(:,10), padding(:,1), ...
    padding(:,1), ch(:,11), padding(:,1), ...
    padding(:,1:4), ch(:,13), ch(:,16), ...
    padding(:,1), ch(:,14), padding(:,1), ...
    padding(:,1), ch(:,15), padding(:,1), ...
    padding(:,1:4), ch(:,17), ch(:,20), ...
    padding(:,1), ch(:,18), padding(:,1), ...
    padding(:,1), ch(:,19), padding(:,1)];