function modifiedCh = modifyChannel(ch)
ch_size = size(ch);
padding = zeros(ch_size(1), 10);

modifiedCh = [padding(:,1:6), ...
    padding(:,1), ch(:,21:22), ...
    padding(:,1:3), ...
    padding(:,1:4), ch(:,1), padding(:,1), ...
    padding(:,1:2), ch(:,2), ...
    padding(:,1:2), ch(:,3), ...
    padding(:,1:4), ch(:,5), padding(:,1), ...
    padding(:,1), ch(:,6), padding(:,1), ...
    padding(:,1), ch(:,7), padding(:,1), ...
    padding(:,1:4), ch(:,8), padding(:,1), ...
    padding(:,1), ch(:,9), padding(:,1), ...
    padding(:,1), ch(:,10), padding(:,1), ...
    padding(:,1:4), ch(:,12), padding(:,1), ...
    padding(:,1), ch(:,13), padding(:,1), ...
    padding(:,1), ch(:,14), padding(:,1), ...
    padding(:,1:4), ch(:,16), padding(:,1), ...
    padding(:,1), ch(:,17), padding(:,1), ...
    padding(:,1), ch(:,18), padding(:,1)];