function out = parseFile( fileName )
% function data = parseFile( fileName )
% Parses the files generated by IGS suits.
%
% Inputs:
% <fileName>    Full path to the BVH file to be read.
%
% Outputs:
% <data>        NxD matrix of data read from the file.
% 

data = load(fileName);
% this is recorded in the main loop, when data gets stored
systemTime = getMilliSecondTime( data(:, 1:4) ); 
% this is recorded on the local eye-tracker server when eye-tracking data
% is collected. 
serverTime = data(:, 5)/1e6;

% thus server time is used as actually when gaze data recorded, but
% realigned to system time, which has sync points related to suit glove
% etc.

time = serverTime - serverTime(1) + systemTime(1);
out.systemTime=systemTime;
out.serverTime=serverTime;

out.time=time;
out.data=[systemTime,data(:,6:32)];
out.markers.ID=data(find(data(:,end)),end); % marker IDs (1=sync pnt, 2calibpnt)
out.markers.time=out.time(find(data(:,end))); %marker associated timestamps

end